site_name: aiTechnicalWriter Portfolio
repo_url: https://github.com/aiTechnicalWriter/aitechnicalwriter.github.io
site_url: https://aitechnicalwriter.github.io/aitw-portfolio/
use_directory_urls: false
docs_dir: docs

theme:
  name: material
  features:
    - navigation.sections
  palette:
    scheme: default



markdown_extensions:
  - tables
  - fenced_code

nav:
  - Home: index.md
  - API Docs:
      - Conceptual Guide: api-docs/explanation-conceptual-guide.md
      - Developer Quickstart: api-docs/howto-developer-quickstart.md
      - API Reference: api-docs/reference-api.md
      - Endpoint Overview: api-docs/endpoint-overview.md
  - Architecture:
      - C4 Model: architecture/c4-model.md
  - Workflows:
      - Software Development Lifecycle (SDLC): workflows/sdlc.md
  - Strategy:
      - Documentation Roadmap: strategy/documentation-roadmap.md
      - Metrics Case Study: strategy/metrics-case-study.md
      - Style Guide Excerpt: style-guide/style-guide-excerpt.md
  - User Guide:
      - Correct Transaction Error: user-guide/howto-correct-transaction-error.md
      - Reference Fields: user-guide/reference-fields.md
      - Customer Lookup Tutorial: user-guide/tutorial-customer-lookup.md
# - Style Guide:
#      - Code & Syntax Guide: style-guide/code-syntax-guide.md
#      - Voice & Tone Guidelines: style-guide/voice-and-tone.md
#      - Error Messaging Guidelines: style-guide/error-messaging.md
#      - UI Terminology Standards: style-guide/ui-terminology.md
#      - Content Types: style-guide/content-types.md

plugins:
  - search
  - swagger-ui-tag
  - macros:
      include_dir: docs

# Force MkDocs to treat this as a user site
remote_branch: gh-pages
remote_name: origin
